default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: file_parser_development;
  username: root
  password:

test:
  <<: *default
  database: file_parser_test;
  username: root
  password:
